apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
   - port: 80
     targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret
          mountPath: /secure
          readOnly: true
        - name: config
          mountPath: "/etc/nginx/config.conf"
          subPath: config.conf
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp /secure/ssl_cert /etc/nginx/ssl.crt"]
      volumes:
        - name: secret
          secret:
            secretName: ssl-cert 
        - name: config
          configMap:
            name: conf
